export const INTERPRETATION_WORKER_GROUP = "interpretation:workers";
export const INTERPRETATION_WORKER_BATCH_SIZE = 5;
export const INTERPRETATION_WORKER_BLOCK_MS = 5000;
export const INTERPRETATION_WORKER_IDLE_CLAIM_MS = 30000;
export const INTERPRETATION_WORKER_MAX_RETRY = 5;
